springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /

stocks_api:
  base_url: "https://www.alphavantage.co"

webhookProxy:
  timeout: 10000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ID
            client-secret: SECRET
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
